# Generated by Django 4.0.4 on 2022-05-18 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado.', verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='modified at')),
                ('nit', models.CharField(error_messages={'unique': 'Ya existe una empresa con este Nit.'}, max_length=20, unique=True, verbose_name='Nit de la empresa')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre de la empresa')),
                ('direccion', models.CharField(max_length=32, verbose_name='Dirección de la empresa')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Número no válido.', regex='\\+?1?\\d{10,12}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Designa si la empresa está o no activa. Desmarcar esto en lugar de eliminar una empresa.')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
